name: Continuos Integration

on:
  pull_request:
    branches:
      ['main', 'develop']

jobs: 
  unify-front-continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: action/setup-node@v2
        with:
          node-version: 20.x
      - name: run install and build
        run: |
          npm install
          npm run build